Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

foreach ($tool in @('az', 'azd')) {
  if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
    throw "Required command '$tool' is not available."
  }
}

$environmentValues = @{}
$environmentLines = & azd env get-values
if ($LASTEXITCODE -ne 0) {
  throw 'Unable to load the AZD environment values.'
}

$environmentLines | ForEach-Object {
  if ($_ -match '^(?<key>[^=]+)=(?<value>.*)$') {
    $environmentValues[$matches.key] = $matches.value -replace '^"|"$'
  }
}

function Get-RequiredEnvironmentValue([string]$Name) {
  if (-not $environmentValues.ContainsKey($Name) -or [string]::IsNullOrWhiteSpace($environmentValues[$Name])) {
    throw "Required AZD environment value '$Name' is not set."
  }

  return $environmentValues[$Name]
}

$resourceGroup = Get-RequiredEnvironmentValue 'AZURE_RESOURCE_GROUP'
$subscriptionId = Get-RequiredEnvironmentValue 'AZURE_SUBSCRIPTION_ID'
$functionAppName = Get-RequiredEnvironmentValue 'AZURE_FUNCTION_APP_NAME'
$systemTopicName = Get-RequiredEnvironmentValue 'EVENT_GRID_SYSTEM_TOPIC_NAME'
$eventSubscriptionName = Get-RequiredEnvironmentValue 'EVENT_GRID_SUBSCRIPTION_NAME'
$containerName = Get-RequiredEnvironmentValue 'SOURCE_CONTAINER_NAME'
$blobsExtensionKey = $null
$endpointUrl = $null

try {
  $blobsExtensionKey = (& az functionapp keys list `
    --name $functionAppName `
    --resource-group $resourceGroup `
    --subscription $subscriptionId `
    --query 'systemKeys.blobs_extension' `
    --output tsv `
    --only-show-errors).Trim()

  if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($blobsExtensionKey)) {
    throw 'Unable to retrieve the Functions blobs_extension system key.'
  }

  $endpointUrl = "https://${functionAppName}.azurewebsites.net/runtime/webhooks/blobs?functionName=Host.Functions.process_blob_upload&code=$([uri]::EscapeDataString($blobsExtensionKey))"
  $subjectPrefix = "/blobServices/default/containers/${containerName}/blobs/"

  # The system key is generated by Functions after code deployment and is never persisted or logged.
  & az eventgrid system-topic event-subscription show `
    --name $eventSubscriptionName `
    --resource-group $resourceGroup `
    --subscription $subscriptionId `
    --system-topic-name $systemTopicName `
    --output none `
    --only-show-errors 2>$null
  $subscriptionCommand = if ($LASTEXITCODE -eq 0) { 'update' } else { 'create' }

  & az eventgrid system-topic event-subscription $subscriptionCommand `
    --name $eventSubscriptionName `
    --resource-group $resourceGroup `
    --subscription $subscriptionId `
    --system-topic-name $systemTopicName `
    --endpoint-type webhook `
    --endpoint $endpointUrl `
    --included-event-types 'Microsoft.Storage.BlobCreated' `
    --subject-begins-with $subjectPrefix `
    --subject-ends-with '.json.log.gz' `
    --output none `
    --only-show-errors

  if ($LASTEXITCODE -ne 0) {
    throw 'Unable to create or update the Event Grid webhook subscription.'
  }

  Write-Output 'Event Grid blob subscription configured.'
}
finally {
  $endpointUrl = $null
  $blobsExtensionKey = $null
  $environmentValues.Clear()
  $environmentLines = $null
  Remove-Variable endpointUrl, blobsExtensionKey, environmentLines -ErrorAction SilentlyContinue
}
