#!/usr/bin/env sh
set -eu

for command in az azd; do
  command -v "$command" >/dev/null 2>&1 || {
    printf '%s\n' "Required command '$command' is not available." >&2
    exit 1
  }
done

resource_group=''
subscription_id=''
function_app_name=''
system_topic_name=''
event_subscription_name=''
container_name=''
blobs_extension_key=''
endpoint_url=''
environment_values=''

cleanup() {
  blobs_extension_key=''
  endpoint_url=''
  environment_values=''
}
trap cleanup EXIT

environment_values="$(azd env get-values)" || {
  printf '%s\n' 'Unable to load the AZD environment values.' >&2
  exit 1
}

while IFS='=' read -r key value; do
  value=${value#\"}
  value=${value%\"}
  case "$key" in
    AZURE_RESOURCE_GROUP) resource_group=$value ;;
    AZURE_SUBSCRIPTION_ID) subscription_id=$value ;;
    AZURE_FUNCTION_APP_NAME) function_app_name=$value ;;
    EVENT_GRID_SYSTEM_TOPIC_NAME) system_topic_name=$value ;;
    EVENT_GRID_SUBSCRIPTION_NAME) event_subscription_name=$value ;;
    SOURCE_CONTAINER_NAME) container_name=$value ;;
  esac
done <<EOF
$environment_values
EOF

: "${resource_group:?Required AZD environment value AZURE_RESOURCE_GROUP is not set.}"
: "${subscription_id:?Required AZD environment value AZURE_SUBSCRIPTION_ID is not set.}"
: "${function_app_name:?Required AZD environment value AZURE_FUNCTION_APP_NAME is not set.}"
: "${system_topic_name:?Required AZD environment value EVENT_GRID_SYSTEM_TOPIC_NAME is not set.}"
: "${event_subscription_name:?Required AZD environment value EVENT_GRID_SUBSCRIPTION_NAME is not set.}"
: "${container_name:?Required AZD environment value SOURCE_CONTAINER_NAME is not set.}"

blobs_extension_key="$(az functionapp keys list \
  --name "$function_app_name" \
  --resource-group "$resource_group" \
  --subscription "$subscription_id" \
  --query 'systemKeys.blobs_extension' \
  --output tsv \
  --only-show-errors)"

[ -n "$blobs_extension_key" ] || {
  printf '%s\n' 'Unable to retrieve the Functions blobs_extension system key.' >&2
  exit 1
}

# The system key is generated by Functions after code deployment and is never persisted or logged.
if az eventgrid system-topic event-subscription show \
  --name "$event_subscription_name" \
  --resource-group "$resource_group" \
  --subscription "$subscription_id" \
  --system-topic-name "$system_topic_name" \
  --output none \
  --only-show-errors >/dev/null 2>&1; then
  subscription_command='update'
else
  subscription_command='create'
fi
endpoint_url="https://${function_app_name}.azurewebsites.net/runtime/webhooks/blobs?functionName=Host.Functions.process_blob_upload&code=${blobs_extension_key}"
subject_prefix="/blobServices/default/containers/${container_name}/blobs/"

az eventgrid system-topic event-subscription "$subscription_command" \
  --name "$event_subscription_name" \
  --resource-group "$resource_group" \
  --subscription "$subscription_id" \
  --system-topic-name "$system_topic_name" \
  --endpoint-type webhook \
  --endpoint "$endpoint_url" \
  --included-event-types 'Microsoft.Storage.BlobCreated' \
  --subject-begins-with "$subject_prefix" \
  --subject-ends-with '.json.log.gz' \
  --output none \
  --only-show-errors

printf '%s\n' 'Event Grid blob subscription configured.'
